server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 35s
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  # OAuth 로그인
  security:
    oauth2:
      kakao:
        client-id: ${REST_API_PRIVATE_KEY}
        client-secret: ${CLIENT_SECRET_KEY}
        scope:
          - account_email
          - profile_nickname
        authorization-grant-type: authorization_code
        redirect-uri: http://localhost:8080/oauth/kakao/redirect
        client-name: Kakao
        client-authentication-method: POST
        url:
          login: https://kauth.kakao.com/oauth/authorize
          token: https://kauth.kakao.com/oauth/token
          profile: https://kapi.kakao.com/v2/user/me
          unlink: https://kapi.kakao.com/v1/user/unlink

logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: INFO
    kr.co.user.model: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%t][%logger.%method:line%line] - %msg%n"
  file:
    name: "/tmp/logs/134talk.log"